server:
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
spring:
  datasource:
    password: asd123
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/marketplace?useUnicode=yes&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  mvc:
    ignore-default-model-on-redirect: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: mirrorsmarketplace@gmail.com
    password: Srorrim1234

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000